name: Build on Different .NET Versions and Linux

on: workflow_dispatch


jobs:
  build: 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dotnet-version: [7.0, 6.0]
        
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          version: ${{matrix.version}}

      - name: Restore dependencies
        run: dotnet restore ./Todo.Tests/Todo.Tests/Csproj
  
      - name: Build
        run: dotnet build ./Todo.Tests/Todo.Tests/Csproj --no-restore
  
      - name: Run tests 
        run: dotnet test ./Todo.Tests/Todo.Tests/Csproj --no-build --logger "html" --results-directory "test_results"
