name: Build on Different .NET Versions and Linux

on: push


jobs:
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [8.0, 7.0, 6.0]
        
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          version: ${{matrix.version}}

      - name: Restore dependencies
        run: dotnet restore ./ToDo.Tests/ToDo.Tests.csproj
  
      - name: Build
        run: dotnet build ./ToDo.Tests/ToDo.Tests.csproj --no-restore
  
      - name: Run tests 
        run: dotnet test ./ToDo.Tests/ToDo.Tests.csproj --no-build --logger "html" --results-directory "test_results"
