name: Build on Different .NET Versions and Linux

on: workflow_dispatch


jobs:
  build: 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        version: [8.0, 7.0, 6.0]
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with: 
          version: ${{matrix.version}}

      - name: Restore dependencies
        run: dotnet restore
  
      - name: Build
        run: dotnet build --configuration Release
  
      - name: Run tests
        run: dotnet test
