name: Reminder

on:
  schedule: 
    - cron: '*/1 11 * 11 1'

jobs:
  birthday-reminder:
  
    runs-on: ubuntu-latest

    steps:
      - name: Run reminder script
        run: |
          bash C:\Users\chgra\OneDrive\Systemutveckling .net Vis Stud\Clean Code & Devops\ToDoWithDanielsStructure\birthday_reminder
